[package]
name = "fei"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Fei"
homepage = "https://github.com/fei-rs/fei"
repository = "https://github.com/fei-rs/fei"
readme = "README.md"
